redirectsOrigin = "config"
headers = []

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "C:\\Users\\wangxiaoping\\Documents\\New project\\ai-tool-navigator\\.next"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]
NEXT_RUNTIME = "nodejs"
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api/*"
to = "/api/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/admin/*"
to = "/admin/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]